server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://sandbox-db.cbranowldplf.us-east-2.rds.amazonaws.com:3306/campus_navi_db
    username: sandbox_db_admin
    password: ktUJ2LAzLakek9GjD93e
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
